#!/bin/bash
# ============================================================
#  BD — BetterDriver
#  deploy.sh — One-command deployment script
#  Domain: betterdriver.co.za
#  Port:   3003
# ============================================================

set -e

SITE_NAME="BD"
DOMAIN="betterdriver.co.za"
PORT=3003
APP_NAME="bd-site"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "=============================================="
echo "  BetterDriver — Deployment Script"
echo "=============================================="
echo ""

# ── Step 1: Check Node.js ──────────────────────────────────
echo "Checking Node.js..."
if ! command -v node &> /dev/null; then
  echo -e "${RED}ERROR: Node.js is not installed.${NC}"
  echo "Install it with: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs"
  exit 1
fi
NODE_VER=$(node -v)
echo -e "${GREEN}Node.js found: $NODE_VER${NC}"

# ── Step 2: Check PM2 ─────────────────────────────────────
echo ""
echo "Checking PM2..."
if ! command -v pm2 &> /dev/null; then
  echo -e "${YELLOW}PM2 not found. Installing globally...${NC}"
  npm install -g pm2
fi
echo -e "${GREEN}PM2 ready.${NC}"

# ── Step 3: Verify standalone build ───────────────────────
echo ""
echo "Verifying build..."
if [ ! -f ".next/standalone/server.js" ]; then
  echo -e "${RED}ERROR: .next/standalone/server.js not found.${NC}"
  echo "The build appears to be incomplete. Please re-download the ZIP and try again."
  exit 1
fi
echo -e "${GREEN}Standalone build verified.${NC}"

# ── Step 4: Verify static assets in standalone ────────────
echo ""
echo "Verifying static assets..."
if [ ! -d ".next/standalone/.next/static" ]; then
  echo "Copying .next/static into standalone..."
  cp -r .next/static .next/standalone/.next/static
fi
echo -e "${GREEN}Static assets verified.${NC}"

# ── Step 5: Create .env.local ─────────────────────────────
echo ""
echo "=============================================="
echo "  Environment Variables Setup"
echo "  (Press Enter to skip optional variables)"
echo "=============================================="
echo ""

ENV_FILE=".next/standalone/.env.local"

if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}An existing .env.local was found.${NC}"
  read -p "Overwrite it? (y/N): " OVERWRITE
  if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
    echo "Keeping existing .env.local."
  else
    rm "$ENV_FILE"
  fi
fi

if [ ! -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}REQUIRED — Supabase${NC}"
  read -p "  NEXT_PUBLIC_SUPABASE_URL (e.g. https://xxxx.supabase.co): " SUPABASE_URL
  read -p "  NEXT_PUBLIC_SUPABASE_ANON_KEY: " SUPABASE_ANON_KEY
  read -p "  SUPABASE_SERVICE_ROLE_KEY (server-side key, from Supabase Settings > API): " SUPABASE_SERVICE_KEY

  echo ""
  echo -e "${YELLOW}REQUIRED — JWT Secret${NC}"
  read -p "  JWT_SECRET (any long random string, e.g. run: openssl rand -hex 32): " JWT_SECRET

  echo ""
  echo -e "${YELLOW}OPTIONAL — Email (Resend)${NC}"
  read -p "  RESEND_API_KEY (leave blank to skip): " RESEND_API_KEY
  read -p "  RESEND_FROM_EMAIL (e.g. noreply@betterdriver.co.za, leave blank to skip): " RESEND_FROM

  echo ""
  echo -e "${YELLOW}OPTIONAL — Moodle LMS Integration${NC}"
  echo "  (Required for Driver University course content)"
  read -p "  MOODLE_BASE_URL (e.g. https://learn.betterdriver.co.za, leave blank to skip): " MOODLE_URL
  read -p "  MOODLE_TOKEN (Web Service token from Moodle admin, leave blank to skip): " MOODLE_TOKEN

  echo ""
  echo -e "${YELLOW}OPTIONAL — Payments (Paystack)${NC}"
  read -p "  PAYSTACK_SECRET_KEY (leave blank to skip): " PAYSTACK_SECRET_KEY
  read -p "  NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY (leave blank to skip): " PAYSTACK_PUBLIC_KEY

  cat > "$ENV_FILE" << EOF
# BD — BetterDriver
# Generated by deploy.sh on $(date)

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY}

# Auth
JWT_SECRET=${JWT_SECRET}

# Email
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_FROM_EMAIL=${RESEND_FROM}

# Moodle
MOODLE_BASE_URL=${MOODLE_URL}
MOODLE_TOKEN=${MOODLE_TOKEN}

# Payments
PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}

# Server
PORT=${PORT}
HOSTNAME=0.0.0.0
EOF

  echo ""
  echo -e "${GREEN}.env.local created at $ENV_FILE${NC}"
fi

# ── Step 6: Start with PM2 ────────────────────────────────
echo ""
echo "Starting server with PM2..."

pm2 stop $APP_NAME 2>/dev/null || true
pm2 delete $APP_NAME 2>/dev/null || true

cd .next/standalone
PORT=$PORT HOSTNAME=0.0.0.0 pm2 start server.js \
  --name "$APP_NAME" \
  --env production \
  --max-memory-restart 512M \
  --restart-delay 3000
cd ../..

pm2 save

echo ""
echo -e "${GREEN}=============================================="
echo "  BetterDriver is running!"
echo "  Local:  http://localhost:${PORT}"
echo "  Public: https://${DOMAIN} (after Nginx + SSL setup)"
echo ""
echo "  PM2 commands:"
echo "    pm2 status          — check running processes"
echo "    pm2 logs $APP_NAME  — view live logs"
echo "    pm2 restart $APP_NAME — restart the server"
echo -e "==============================================${NC}"
echo ""
echo "Next step: Configure Nginx using the nginx.conf file in this directory."
echo "Then run: sudo certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
echo ""
